spring:
  application:
    name: ToDo

  datasource:
    url: jdbc:postgresql://localhost:5433/ToDo
    driver-class-name: org.postgresql.Driver
    username: todo
    password: todo1
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080